import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Sparkles, ArrowRight, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

const artifacts = [
  { type: 'Infographic', desc: 'Visual summaries of your documents' },
  { type: 'Mind Map', desc: 'Concept hierarchies and relationships' },
  { type: 'Study Guide', desc: 'Revision material from any document' },
  { type: 'Flashcards', desc: 'Question and answer cards for learning' },
  { type: 'Concept Visual', desc: 'Educational visuals generated by AI' },
  { type: 'Executive Brief', desc: 'Concise professional summaries' },
];

export function StudioOverviewPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-8 md:px-10">
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <h1 className="font-display text-3xl md:text-4xl">AI Studio</h1>
        <p className="mt-2 text-muted-foreground">Generate visual learning artifacts from your documents.</p>
      </motion.div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {artifacts.map((a, i) => (
          <motion.div key={a.type} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }}>
            <Card className="glass group p-5 transition-colors hover:border-primary/30">
              <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg border border-primary/20 bg-primary/5 transition-transform group-hover:scale-110">
                <Sparkles size={20} className="text-primary" />
              </div>
              <h3 className="font-display text-base">{a.type}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{a.desc}</p>
            </Card>
          </motion.div>
        ))}
      </div>

      <Card className="glass mt-8 p-8 text-center">
        <FileText size={32} className="mx-auto mb-3 text-primary" />
        <p className="font-display text-lg">Open a document to generate artifacts</p>
        <p className="mt-1 text-sm text-muted-foreground">AI Studio is available inside each document workspace.</p>
        <Link to="/dashboard/documents" className="mt-4 inline-block">
          <Button variant="outline" className="gap-2">Browse Documents <ArrowRight size={16} /></Button>
        </Link>
      </Card>
    </div>
  );
}
